# Sentry alert data

Created: 2019-01-15

Last modified: 2019-01-15

# Methods

In [3]:
%matplotlib inline
import os
import sys
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.reset_orig()

/local/home/Asif/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:855: MatplotlibDeprecationWarning:
examples.directory is deprecated; in the future, examples will be found relative to the 'datapath' directory.
  "found relative to the 'datapath' directory.".format(key))
/local/home/Asif/anaconda3/lib/python3.7/site-packages/matplotlib/__init__.py:846: MatplotlibDeprecationWarning:
The text.latex.unicode rcparam was deprecated in Matplotlib 2.2 and will be removed in 3.1.
  "2.2", name=key, obj_type="rcparam", addendum=addendum)

In [4]:
from textwrap import dedent
import findspark
import os
def _formulate_pyspark_submit_args(submit_args=None):
    pass
def _parse_master(pyspark_submit_args):
    sargs = pyspark_submit_args.split()
    for j,sarg in enumerate(sargs):
        if sarg == "--master":
            try:
                return sargs[j+1]
            except:
                raise Exception("Could not parse master from PYSPARK_SUBMIT_ARGS")
    raise Exception("Could not parse master from PYSPARK_SUBMIT_ARGS")
def initialize_spark(appName="MyApp",submit_args=None):
    """
    This function assumes you already have SPARK_HOME and PYSPARK_SUBMIT_ARGS environment variables set
    """
    if "SPARK_HOME" not in os.environ:
        raise Exception("SPARK_HOME environmental variable not set.")
    if 'PYSPARK_SUBMIT_ARGS' not in os.environ:
        os.environ['PYSPARK_SUBMIT_ARGS'] = '--master local[12] --driver-memory 8g --executor-memory 8g pyspark-shell'
    if "PYSPARK_SUBMIT_ARGS" not in os.environ:
        raise Exception(
                dedent("""\
                       PYSPARK_SUNBMIT_ARGS environmental variable not set.
                       
                       As an example:
                       export PYSPARK_SUBMIT_ARGS = " --master local[8] --driver-memory 8g --executor-memory 8g pyspark-shell"
                       """))
    findspark.init()
    spark_master = _parse_master(os.environ["PYSPARK_SUBMIT_ARGS"])
    from pyspark.sql import SparkSession
    spark = SparkSession\
                .builder\
                .master(spark_master)\
                .appName("MyApp")\
                .getOrCreate()
    return spark

spark = initialize_spark()

spark

IndexError: list index out of range

In [ ]:
import pyarrow.parquet as pq
from pyspark.sql import SQLContext
sq = SQLContext(spark)

# Load data

In [9]:
PATH = '/home/p2017-999/acs_data/processed_data/eICU/Sentry/'
!ls {PATH}

Event  Final  Outcome  recombinedStayNew.csv  recombinedStayOld.csv

In [10]:
recombinedStayNew = pd.read_csv(os.path.join(PATH,'recombinedStayNew.csv'))

In [12]:
recombinedStayNew.shape

(2358086, 43)

In [14]:
recombinedStayNew.columns

Index(['TableName', 'dummyStayID', 'patientHealthSystemStayID',
       'patientUnitStayIDFirst', 'patientUnitStayIDLast', 'recombinedFlag',
       'gender', 'age', 'ethnicity', 'hospitalID', 'wardID',
       'apacheAdmissionDx', 'admissionHeight', 'hospitalAdmitYear',
       'hospitalAdmitTime', 'hospitalAdmitOffset', 'hospitalAdmitSource',
       'hospitalDischargeYear', 'hospitalDischargeTime',
       'hospitalDischargeOffset', 'hospitalDischargeLocation',
       'hospitalDischargeStatus', 'unitType', 'unitAdmitYear', 'unitAdmitTime',
       'unitAdmitOffset', 'unitAdmitSource', 'unitVisitNumber', 'unitStayType',
       'admissionWeight', 'dischargeWeight', 'unitDischargeYear',
       'unitDischargeTime', 'unitDischargeOffset', 'unitDischargeLocation',
       'unitDischargeStatus', 'cmoFlag', 'dnrFlag', 'readmitFlag',
       'timeToReadmission', 'icuDischargeInternal',
       'dischargeLocationMissingID', 'drsFlag'],
      dtype='object')

In [16]:
hospitalids = recombinedStayNew.hospitalID.unique()

In [23]:
recombinedStayNew.head()

,TableName,dummyStayID,patientHealthSystemStayID,patientUnitStayIDFirst,patientUnitStayIDLast,recombinedFlag,gender,age,ethnicity,hospitalID,...,unitDischargeOffset,unitDischargeLocation,unitDischargeStatus,cmoFlag,dnrFlag,readmitFlag,timeToReadmission,icuDischargeInternal,dischargeLocationMissingID,drsFlag
0,recombinedStay,1,128894,141136,141136,0,Female,81,Caucasian,73,...,17744,Floor,Alive,0,0,0,NaN,1,NaN,0
1,recombinedStay,2,128905,141151,141151,0,Male,67,Caucasian,56,...,4352,Home,Alive,0,0,0,NaN,0,NaN,0
2,recombinedStay,3,128919,141168,141168,0,Female,70,Caucasian,59,...,3596,Death,Expired,0,0,0,NaN,0,NaN,1
3,recombinedStay,4,128921,141170,141170,0,Male,75,Caucasian,73,...,8310,Floor,Alive,0,1,0,NaN,1,NaN,0
4,recombinedStay,5,128931,141183,141183,0,Female,29,African American,73,...,4014,Home,Alive,0,0,0,NaN,0,NaN,1

In [30]:
k = recombinedStayNew.duplicated(['patientHealthSystemStayID'])
dids = recombinedStayNew.loc[k].patientHealthSystemStayID.unique()

In [38]:
recombinedStayNew.loc[recombinedStayNew.patientHealthSystemStayID == dids[3]]

,TableName,dummyStayID,patientHealthSystemStayID,patientUnitStayIDFirst,patientUnitStayIDLast,recombinedFlag,gender,age,ethnicity,hospitalID,...,unitDischargeOffset,unitDischargeLocation,unitDischargeStatus,cmoFlag,dnrFlag,readmitFlag,timeToReadmission,icuDischargeInternal,dischargeLocationMissingID,drsFlag
49,recombinedStay,50,128902,141146,141146,0,Male,86,Caucasian,71,...,41849,Floor,Alive,0,1,0,NaN,1,NaN,1
65,recombinedStay,66,128902,141145,141145,0,Male,86,Caucasian,71,...,10004,Floor,Alive,0,0,0,NaN,1,NaN,1

In [42]:
recombinedStayNew.loc[recombinedStayNew.patientUnitStayIDFirst != recombinedStayNew.patientUnitStayIDLast]

,TableName,dummyStayID,patientHealthSystemStayID,patientUnitStayIDFirst,patientUnitStayIDLast,recombinedFlag,gender,age,ethnicity,hospitalID,...,unitDischargeOffset,unitDischargeLocation,unitDischargeStatus,cmoFlag,dnrFlag,readmitFlag,timeToReadmission,icuDischargeInternal,dischargeLocationMissingID,drsFlag
164,recombinedStay,165,129039,141313,141314,1,Male,45,Caucasian,73,...,1078,Death,Expired,0,0,0,NaN,0,NaN,0
224,recombinedStay,225,129174,141473,141472,1,Female,49,Hispanic,73,...,21301,Floor,Alive,0,0,0,NaN,1,NaN,0
321,recombinedStay,322,129280,141609,141612,1,Male,75,Caucasian,73,...,8575,Floor,Alive,0,0,1,5804.0,1,NaN,0
322,recombinedStay,323,129290,141623,141626,1,Male,62,Caucasian,60,...,4721,stepdown/other,Alive,0,0,0,NaN,1,NaN,1
329,recombinedStay,330,129349,141710,141712,1,Female,44,Caucasian,63,...,1501,stepdown/other,Alive,0,1,0,NaN,1,NaN,0
351,recombinedStay,352,129298,141637,141638,1,Female,61,Caucasian,73,...,7784,NaN,NaN,0,0,0,NaN,0,2.0,0
392,recombinedStay,393,129459,141854,141855,1,Female,31,African American,73,...,14057,Floor,Alive,0,0,0,NaN,1,NaN,0
416,recombinedStay,417,129314,141661,141659,1,Male,60,Caucasian,73,...,3265,stepdown/other,Alive,0,1,0,NaN,1,NaN,1
562,recombinedStay,563,129482,141893,141892,1,Male,84,Caucasian,73,...,7628,Floor,Alive,0,0,0,NaN,1,NaN,0
627,recombinedStay,628,129527,141947,141948,1,Female,46,Caucasian,73,...,9028,Floor,Alive,0,0,0,NaN,1,NaN,1
637,recombinedStay,638,129296,141633,141635,1,Male,60,Caucasian,73,...,34142,Floor,Alive,0,1,1,6898.0,1,NaN,1
685,recombinedStay,686,129530,141954,141955,1,Male,54,Caucasian,73,...,12709,Floor,Alive,0,1,0,NaN,1,NaN,0
735,recombinedStay,736,129564,141994,141993,1,Female,66,Caucasian,73,...,1816,Floor,Alive,0,0,1,5106.0,1,NaN,0
757,recombinedStay,758,129610,142068,142067,1,Female,71,African American,73,...,111228,Floor,Alive,0,0,0,NaN,1,NaN,1
801,recombinedStay,802,129730,142217,142216,1,Female,79,Caucasian,68,...,5177,Floor,Alive,0,0,0,NaN,1,NaN,0
804,recombinedStay,805,129777,142278,142277,1,Female,57,Caucasian,73,...,29975,Floor,Alive,0,0,0,NaN,1,NaN,1
814,recombinedStay,815,129650,142115,142114,1,Female,54,Caucasian,73,...,2147,Floor,Alive,0,0,0,NaN,1,NaN,0
823,recombinedStay,824,129741,142230,142229,1,Female,78,Caucasian,73,...,18658,Floor,Alive,0,0,0,NaN,1,NaN,1
864,recombinedStay,865,129684,142156,142155,1,Female,77,African American,73,...,4482,Floor,Alive,0,0,0,NaN,1,NaN,1
866,recombinedStay,867,129707,142186,142187,1,Male,62,Caucasian,73,...,7468,Floor,Alive,0,0,0,NaN,1,NaN,1
879,recombinedStay,880,129709,142189,142190,1,Male,54,Caucasian,73,...,4495,Floor,Alive,0,0,0,NaN,1,NaN,0
916,recombinedStay,917,129750,142241,142240,1,Female,61,African American,73,...,9784,Floor,Alive,0,0,0,NaN,1,NaN,0
967,recombinedStay,968,129788,142290,142291,1,Female,80,Caucasian,73,...,17363,Floor,Alive,0,1,0,NaN,1,NaN,0
996,recombinedStay,997,129756,142248,142249,1,Male,49,African American,73,...,6689,Floor,Alive,0,0,0,NaN,1,NaN,1
997,recombinedStay,998,129775,142273,142274,1,Male,55,African American,73,...,17858,Floor,Alive,0,0,0,NaN,1,NaN,1
1014,recombinedStay,1015,129843,142367,142365,1,Female,72,Caucasian,73,...,29892,Floor,Alive,0,0,0,NaN,1,NaN,0
1028,recombinedStay,1029,129802,142310,142309,1,Male,70,Caucasian,73,...,14154,Floor,Alive,0,0,0,NaN,1,NaN,0
1048,recombinedStay,1049,129961,142514,142515,1,Male,42,Caucasian,73,...,4251,Floor,Alive,0,0,0,NaN,1,NaN,1
1204,recombinedStay,1205,129927,142475,142474,1,Female,67,Caucasian,73,...,21087,stepdown/other,Alive,0,1,0,NaN,1,NaN,1
1250,recombinedStay,1251,130030,142611,142610,1,Male,79,Caucasian,73,...,179,Floor,Alive,0,0,0,NaN,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2357296,recombinedStay,2357297,2740700,3350576,3350577,1,Female,76,Caucasian,458,...,80117,Floor,Alive,0,0,0,NaN,1,NaN,0
2357303,recombinedStay,2357304,2740751,3350635,3350634,1,Female,72,Caucasian,458,...,5215,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357318,recombinedStay,2357319,2740852,3350746,3350745,1,Male,56,Caucasian,458,...,5133,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357342,recombinedStay,2357343,2741043,3350958,3350959,1,Male,57,Caucasian,458,...,8065,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357356,recombinedStay,2357357,2742609,3352709,3352708,1,Male,42,Caucasian,458,...,6204,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357366,recombinedStay,2357367,2742692,3352798,3352797,1,Female,67,Caucasian,458,...,19159,Floor,Alive,0,0,0,NaN,1,NaN,0
2357367,recombinedStay,2357368,2742701,3352810,3352808,1,Male,59,Caucasian,458,...,27759,Floor,Alive,0,0,1,1306.0,1,NaN,0
2357451,recombinedStay,2357452,2742682,3352783,3352784,1,Female,78,Caucasian,458,...,22423,Floor,Alive,0,0,0,NaN,1,NaN,0
2357504,recombinedStay,2357505,2742820,3352935,3352937,1,Male,67,Caucasian,458,...,11479,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357559,recombinedStay,2357560,2742877,3353001,3353002,1,Male,48,Caucasian,458,...,7291,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357648,recombinedStay,2357649,2742977,3353111,3353110,1,Female,61,African American,458,...,10014,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357689,recombinedStay,2357690,2742860,3352979,3352980,1,Male,32,Other/Unknown,458,...,5392,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357711,recombinedStay,2357712,2742980,3353114,3353115,1,Female,83,Caucasian,458,...,1948,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357713,recombinedStay,2357714,2742997,3353134,3353133,1,Male,83,African American,458,...,7737,Step-Down Unit (SDU),Alive,0,0,0,NaN,1,NaN,0
2357717,recombinedStay,2357718,2743025,3353166,3353165,1,Male,46,Caucasian,458,...,3743,Floor,Alive,0,0,0,NaN,1,NaN,0
2357731,recombinedStay,2357732,2742904,3353033,3353032,1,Male,22,African American,458,...,15631,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357741,recombinedStay,2357742,2743004,3353143,3353141,1,Female,80,Caucasian,458,...,12359,Telemetry,Alive,0,1,0,NaN,1,NaN,0
2357825,recombinedStay,2357826,2743065,3353214,3353215,1,Female,20,African American,458,...,10026,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357843,recombinedStay,2357844,2741317,3351253,3351252,1,Female,85,Caucasian,458,...,14152,Home,Alive,0,1,0,NaN,0,NaN,0
2357847,recombinedStay,2357848,2741350,3351296,3351295,1,Male,52,African American,458,...,4135,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357925,recombinedStay,2357926,2741950,3351964,3351963,1,Male,72,Caucasian,458,...,1851,Floor,Alive,0,0,0,NaN,1,NaN,0
2357949,recombinedStay,2357950,2742129,3352164,3352163,1,Female,39,Caucasian,458,...,2698,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2357956,recombinedStay,2357957,2742168,3352210,3352206,1,Female,63,African American,458,...,126556,Telemetry,Alive,0,0,1,37849.0,1,NaN,0
2357965,recombinedStay,2357966,2742242,3352302,3352299,1,Male,34,African American,458,...,33210,Rehabilitation,Alive,0,0,0,NaN,0,NaN,0
2358035,recombinedStay,2358036,2742743,3352855,3352856,1,Male,60,Caucasian,458,...,6199,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2358045,recombinedStay,2358046,2742832,3352950,3352949,1,Female,49,African American,458,...,4969,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2358051,recombinedStay,2358052,2742876,3353000,3352999,1,Male,65,Caucasian,458,...,2503,Floor,Alive,0,0,0,NaN,1,NaN,0
2358077,recombinedStay,2358078,2743055,3353197,3353199,1,Female,66,Caucasian,458,...,52859,Step-Down Unit (SDU),Alive,0,0,1,182.0,1,NaN,0
2358078,recombinedStay,2358079,2743063,3353212,3353210,1,Male,> 89,Other/Unknown,458,...,25196,Telemetry,Alive,0,0,0,NaN,1,NaN,0
2358080,recombinedStay,2358081,2743074,3353225,3353224,1,Male,66,Caucasian,458,...,13779,Telemetry,Alive,0,0,0,NaN,1,NaN,0

In [43]:
recombinedStayNew.loc[:,['patientHealthSystemStayID','patientUnitStayIDFirst','patientUnitStayIDLast','recombinedFlag','hospitalID']]

,patientHealthSystemStayID,patientUnitStayIDFirst,patientUnitStayIDLast,recombinedFlag
0,128894,141136,141136,0
1,128905,141151,141151,0
2,128919,141168,141168,0
3,128921,141170,141170,0
4,128931,141183,141183,0
5,128933,141185,141185,0
6,128946,141200,141200,0
7,128947,141202,141202,0
8,128960,141217,141217,0
9,128961,141219,141219,0
10,128974,141234,141234,0
11,128975,141236,141236,0
12,128987,141251,141251,0
13,128989,141253,141253,0
14,129002,141268,141268,0
15,129003,141270,141270,0
16,128896,141138,141138,0
17,128909,141156,141156,0
18,128915,141163,141163,0
19,128929,141181,141181,0
20,128936,141188,141188,0
21,128945,141199,141199,0
22,128951,141206,141206,0
23,128956,141213,141213,0
24,128965,141224,141224,0
25,128971,141231,141231,0
26,128977,141238,141238,0
27,128985,141249,141249,0
28,128991,141256,141256,0
29,129007,141274,141274,0
...,...,...,...,...
2358056,2742912,3353042,3353042,0
2358057,2742919,3353049,3353049,0
2358058,2742925,3353056,3353056,0
2358059,2742936,3353067,3353067,0
2358060,2742943,3353074,3353074,0
2358061,2742950,3353081,3353081,0
2358062,2742960,3353092,3353092,0
2358063,2742967,3353099,3353099,0
2358064,2742974,3353106,3353106,0
2358065,2742981,3353117,3353117,0
2358066,2742988,3353124,3353124,0
2358067,2742995,3353131,3353131,0
2358068,2742998,3353135,3353135,0
2358069,2743004,3353142,3353142,0
2358070,2743009,3353149,3353149,0
2358071,2743016,3353156,3353156,0
2358072,2743020,3353160,3353160,0
2358073,2743026,3353167,3353167,0
2358074,2743033,3353174,3353174,0
2358075,2743044,3353185,3353185,0
2358076,2743051,3353192,3353192,0
2358077,2743055,3353197,3353199,1
2358078,2743063,3353212,3353210,1
2358079,2743067,3353217,3353217,0
2358080,2743074,3353225,3353224,1
2358081,2743084,3353235,3353235,0
2358082,2743091,3353242,3353242,0
2358083,2743097,3353249,3353249,0
2358084,2743108,3353260,3353260,0
2358085,2743114,3353267,3353267,0